---
title: "Greece"
author: "Mike"
date: "February 25, 2015"
output: 
  html_document:
    keep_md: yes
---

```{r,echo=FALSE, warning=FALSE, results='hide'}
library(gapminder)
library(ggplot2)
# downdloading 
library(devtools)
library(plyr)
library(dplyr)
# created Geece as an object 
Greek <- gapminder %>%
  filter(year, country == "Greece") %>%
  group_by(country, year) 
# Flitering out country and year from Gapminder
```

```{r, echo=FALSE, warning=FALSE}
str(Greek) 
#Looking at structure
```
```{r,echo=FALSE, warning=FALSE, results='hide'}
#looking at head
head(Greek)
```
```{r,echo=FALSE, warning=FALSE, results='hide'}
ggplot(Greek, aes(x=year, y=gdpPercap, colour=country)) + geom_line() + geom_point() + geom_line(colour = "blue") + ggtitle("Greece GDP per captia") 
```

Plotting Greece GDP per capita by year



```{r}

ggplot(Greek, aes(x=year, y=lifeExp, colour=country)) + geom_line() + geom_point() + geom_line(colour = "blue") + ggtitle("Greece Life Expectancy")

```

Piloting Greece Life expectancy by year



```{r}

ggplot(Greek, aes(x=year, y=pop, colour=country)) + geom_line() + geom_point() + geom_line(colour = "blue") + ggtitle("Greece Population per year")
```


Plotting Greece Population by year

```{r}
Greek <- gapminder %>% 
  mutate(Rategdp = 100*((gdpPercap - lag(gdpPercap)))/gdpPercap) %>%
  filter(country == "Greece") %>%
  filter(year > 1952) 
p1 <-  ggplot(Greek, aes(x=year, y=Rategdp, colour=country)) + geom_line() + geom_point() + geom_line(colour = "blue") + ggtitle("Greece Rate of change on GDP per capita")
p1

```

Rate of change on GDP per capita

```{r}
Greek <- gapminder %>%
  mutate(Ratelife = 100*((lifeExp - lag(lifeExp)))/lifeExp) %>%
  filter(year, country == "Greece") %>%
  filter(year > 1952) 
p2 <-  ggplot(Greek, aes(x=year, y=Ratelife, colour=country )) + geom_line() + geom_point() +  geom_line(colour = "blue") + ggtitle("Greece Change in Life Expectancy" )
p2
```

Rate of change on Life Expectancy by year
```{r}
Greek <- gapminder %>%
  mutate(Ratepop = 100*((pop - lag(pop)))/pop) %>%
  filter(year, country == "Greece") %>%
  filter(year > 1952) 
p3 <-  ggplot(Greek, aes(x=year, y=Ratepop, colour=country )) + geom_line() + geom_point() +  geom_line(colour = "blue") + ggtitle("Greece Change in Population" )
p3
```

rate of change on population

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

multiplot(p1, p2, p3, col = 1)

```









