---
title: "Husky vs S&P"
author: "Mike"
date: "January 28, 2015"
output:
  html_document:
    keep_md: yes
---




```{r}
#loading dependencies
library(quantmod)


```



```{r}
#Retriving Stock symbols Husky and S&P 500 from Yahoo, and using linecharts.
getSymbols("^GSPC", src = "yahoo", from = "2014-01-01")
SP <- GSPC
lineChart(SP, theme = "white")
```

```{r}

 getSymbols("WMT", src = "yahoo", from = "2014-01-01")
Husky <- WMT
lineChart(Husky, theme = "white")
          
```



```{r}
#Checking dimensions and headers for each variable
dim(SP)
head(SP)
dim(Husky)
head(Husky)

```



```{r}
#Pulling out Adjusted stock from each symbol
StockHusky <- Husky[,6]
SPAdj <- GSPC$GSPC.Adjusted

WMT <-data.frame(date=as.character(index(StockHusky)),coredata(StockHusky))
WMT.adj <- WMT %>% 
  select(date,WMT.Adjusted) %>% 
  mutate(WMT.adj = 100*((WMT.Adjusted - lag(WMT.Adjusted)))/WMT.Adjusted)
WMT.adj <- na.omit(WMT.adj[-2])

SP<-data.frame(date=as.character(index(SPAdj)),coredata(SPAdj))
SP.adj <- SP %>% 
  select(date,GSPC.Adjusted) %>% 
  mutate(GSPC = 100*((GSPC.Adjusted - lag(GSPC.Adjusted)))/GSPC.Adjusted)
SP.adj <- na.omit(SP.adj[-2])
CAPM <- as.data.frame(inner_join(WMT.adj, SP.adj, by = "date"))

```



```{r}
#Running a regression
model <- lm(GSPC ~ WMT.adj, data = CAPM)
summary(model)
anova(model)
##By SPAdj estimate is -.016164 with a signifant of .001, the p-value is .001002. For everytime the stock for S&P 500 increases, the Stock for Husky decreases by -.016154 percent. This means that the S&P 500 returns are not strongly correlated...
```

#Running residual plots in time series, and parital plots 

```{r}

plot(residuals(model))
residuals(model)
plot(as.numeric(ts(residuals(model))) ~ as.numeric(ts(SP.adj$GSPC)))


```

#Plot the Model in time series with Fitted vs Residuals

```{r}
plot(as.numeric(ts(fitted(model))), as.numeric(ts(residuals(model))), xlab="Fitted", ylab= "residuals")
```

#Running a qq form, histogram, and autocorrelation

```{r}

qqnorm(residuals(model), ylab="residuals")
qqline(residuals(model), col= "red", lwd = 2)
hist(residuals(model))
acf(residuals(model))
predict(model)

```
